# Análisis de negocio: Ventas, Clientes e Insights
# Archivo de entorno conda para reproducir el ambiente de desarrollo
# ETL con Pandas y SQL - Evidencia de Aprendizaje N° 3

name: ENTORNO-ABP
channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # Análisis de datos
  - pandas>=1.5.0
  - numpy>=1.21.0

  # Visualización
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Procesamiento de archivos Excel
  - openpyxl>=3.0.9

  # Utilidades adicionales
  - python-dateutil>=2.8.0

  # Para desarrollo y Jupyter
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipykernel>=6.0.0
  - ipython>=8.0.0

  # Herramientas adicionales útiles
  - pip

  # Dependencias pip (si no están disponibles en conda)
  - pip:
    # SQLite3 viene incluido con Python, no necesita instalación adicional
    # Todas las dependencias principales están disponibles en conda